packages:
  - apps/*
  - packages/*

catalog:
  "@types/react": ^19.2.7
  "@types/react-dom": ^19.2.3
  "@typescript-eslint/eslint-plugin": ^8.50.1
  "@typescript-eslint/parser": ^8.50.1
  "@vitejs/plugin-react": ^5.1.2
  eslint: ^9.39.2
  eslint-plugin-turbo: ^2.7.2
  prettier: ^3.7.4
  react: ^19.2.3
  react-dom: ^19.2.3
  turbo: ^2.7.2
  typescript: 5.9.3
  vite: ^7.3.0

ignoredBuiltDependencies:
  - package-wth-unnecessary-build-scripts
  - esbuild

#minimumReleaseAge: 10080

minimumReleaseAgeExclude:
  - package-with-critical-hotfix@1.2.3

onlyBuiltDependencies:
  - package-with-necessary-build-scripts

strictDepBuilds: true

#trustPolicy: no-downgrade

trustPolicyExclude:
  - package-that-migrated-cicd@1.2.3
