packages:
  - "apps/*"
  - "packages/*"

# Define a catalog of version ranges.
catalog:
  "@types/react": ^19.2.7
  "@types/react-dom": ^19.2.3
  "@typescript-eslint/eslint-plugin": ^8.50.1
  "@typescript-eslint/parser": ^8.50.1
  "@vitejs/plugin-react": ^5.1.2
  react: ^19.2.3
  react-dom: ^19.2.3
  eslint: ^9.39.2
  eslint-config-prettier: ^10.1.8
  eslint-config-turbo: ^2.7.1
  typescript: 5.9.3
  vite: ^7.3.0

# https://pnpm.io/blog/2025/12/05/newsroom-npm-supply-chain-security

strictDepBuilds: true

onlyBuiltDependencies:
  - package-with-necessary-build-scripts

ignoredBuiltDependencies:
  - package-with-unnecessary-build-scripts

minimumReleaseAge: 10080

minimumReleaseAgeExclude:
  - package-with-critical-hotfix@1.2.3

trustPolicy: no-downgrade

trustPolicyExclude:
  - package-that-migrated-cicd@1.2.3
